server:
  port: 8090

spring:
  profiles:
    active: local
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

error:
  whitelabel:
    enabled: false

amazon:
  associate_id: habuma-20

jpa:
    # 配置 DBMS 类型
    database: MYSQL
    # 配置是否将执行的 SQL 输出到日志
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          # 配置开启自动更新表结构


#开启日志记录（日志文件会在10Mb大小的时候被截断，产生新的日志文件）
logging:
  file: logs/my.log
  level:
    org:
      hiberate: debug