/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2016-03-02 09:20:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.trdapps;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class trdStatDownload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/data/wwwroot/nubia_raf_admin/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1447036445000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resource/css/main.css?v=3\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/resource/css/jquery-ui-1.8.16.custom.css?v=2\" media=\"all\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/resource/css/ui.jqgrid.css\" media=\"all\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"navTil\">\r\n");
      out.write("\t\t<h1 class=\"mainTitle\">第三方应用下载统计</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form_bar\">\r\n");
      out.write("\t\t<form id=\"search_form\">\r\n");
      out.write("\t\t\t<ul class=\"search-list\">\r\n");
      out.write("\t\t\t <li>\r\n");
      out.write("\t\t\t \t<label>时间区间：</label><input id=\"begin_date\" name=\"begin_date\" type=\"text\" class=\"date\" onfocus=\"setday(this)\" readonly=\"readonly\"/> 至 <input id=\"end_date\" class=\"date\" name=\"end_date\" type=\"text\" onfocus=\"setday(this)\" readonly=\"readonly\"/>\r\n");
      out.write("\t\t\t\t<label style=\"margin-left:59px;\">快捷查询：</label><select style=\"cursor:pointer;\" id=\"day_span\" name=\"day_span\">\t\t\r\n");
      out.write("\t\t\t\t\t<option value=''>请选择：</option>\r\n");
      out.write("\t\t\t\t\t<option value='7' >7天</option>\r\n");
      out.write("\t\t\t\t\t<option value='14' >14天</option>\r\n");
      out.write("\t\t\t\t\t<option value='30' >30天</option>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t<label>资源名称：</label><input id=\"search_app_name\" name=\"search_app_name\" type=\"text\" maxlength=\"40\" />\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"opergroup\" name=\"opergroup\" value=\"1\" style=\"display:none\"/>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<input id=\"search_btn\" type=\"button\" value=\"查询\" class=\"reset\" /> \r\n");
      out.write("\t\t\t\t<input id=\"search_reset_btn\" type=\"button\" value=\"重置\" class=\"reset\" />\r\n");
      out.write("\t\t\t\t<input id=\"export_excel_btn\" type=\"button\" value=\"导出报表\" class=\"reset\" style=\"margin-left:93px\"/>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<a style=\"display: none\" class=\"addBtn\" href=\"/url/excel.do\">导出报表</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr><br>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div id=\"chart_report\" style=\"height:400px;margin:0% 2% 0% 0%;\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div  id=\"list\" style=\"margin:0% 2% 0% 0%;\">\r\n");
      out.write("\t\t<table id=\"jqGrid\"></table>\r\n");
      out.write("\t\t<div id=\"jqGridPager\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resource/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resource/js/plugins/grid.locale-cn.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resource/js/plugins/jquery.jqGrid.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resource/js/plugins/jquery.tablednd.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resource/js/plugins/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resource/js/plugins/echarts-all.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resource/js/plugins/DatePicker.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/resource/js/layer.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/trdapps/js/trdStatDownload.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
