/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2016-02-03 09:53:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.apps;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class upgrade_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/data/wwwroot/nubia_raf_admin/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1447036445000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resource/css/main.css?v=3\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"navTil\">\r\n");
      out.write("\t\t<h1 class=\"mainTitle\">升级应用资源</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"popup\" class=\"popup\">\r\n");
      out.write("\t\t<form id=\"urlForm\" action=\"/apps/upgradeApp.do\" method=\"post\"\r\n");
      out.write("\t\t\tencType=\"multipart/form-data\" target=\"uploadFile\">\r\n");
      out.write("\t\t\t<ul class=\"\">\r\n");
      out.write("\t\t\t\t<input name=\"id\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<label>资源名称：</label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.app_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<label>包名：</label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.app_package }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<label>版本号：</label><input name=\"app_version\" id=\"app_version\" type=\"text\" maxlength=\"20\" value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.app_version }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" />\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<label>图标：</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic upload\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.icon_url }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li><label>简介：</label>\r\n");
      out.write("\t\t\t\t<textarea name=\"info\" maxlength=\"200\" class=\"textarea\" disabled=\"disabled\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.info }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea></li>\r\n");
      out.write("\t\t\t\t<li><label>上传文件包：</label>\r\n");
      out.write("\t\t\t\t\t<div id=\"file_upload\" class=\"file_upload\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"url_apk\" class=\"file\" type=\"file\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"filereupload\" class=\"btn reupload\">浏览文件...</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"img-tips\">请确保上传的文件为具有正式签名的APK包(350M以内)。</p>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"group-btn\"><label>&nbsp;</label> \r\n");
      out.write("\t\t\t\t\t<input id=\"back_list\" type=\"button\" value=\"返回\" class=\"reset\" /> \r\n");
      out.write("\t\t\t\t\t<input id=\"submitForm\" type=\"submit\" value=\"提交\" />\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<iframe id=\"uploadFile\" name=\"uploadFile\" style=\"display: none;\"></iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resource/js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resource/js/layer.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#back_list\").click(function() {\r\n");
      out.write("\t\t\tlocation.href = \"/apps/list.do\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#file_upload\").change(function() {\r\n");
      out.write("\t\t\tif (!$(\"#file_upload .file\").val().match(/.apk/i)) {\r\n");
      out.write("\t\t\t\t$(\"#file_upload .file\").val(\"\");\r\n");
      out.write("\t\t\t\ttop.layer.alert('请选择正确的应用文件!');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#submitForm\").click(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar maskLayer = top.layer.load();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar timer = window.setInterval(function() {\r\n");
      out.write("\t\t\t\t\t\t//如果body为空，则认为数据还没返回\r\n");
      out.write("\t\t\t\t\t\tvar _body = $(\"body\",\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#uploadFile\")[0].contentWindow.document);\r\n");
      out.write("\t\t\t\t\t\tif (_body.find(\"*\").length > 0) {\r\n");
      out.write("\t\t\t\t\t\t\twindow.clearInterval(timer);\r\n");
      out.write("\t\t\t\t\t\t\tvar _pre = $(\"pre\", _body);\r\n");
      out.write("\t\t\t\t\t\t\tif (_pre.length > 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar data = $.parseJSON(_pre.text());\r\n");
      out.write("\t\t\t\t\t\t\t\tif (data.code == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttop.layer.alert(\"保存成功\", function(index) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlocation.href = \"/apps/list.do\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttop.layer.close(index);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttop.layer.close(maskLayer);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t_body.empty();\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttop.layer.alert(\"提交失败，原因：\" + data.message[0]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttop.layer.close(maskLayer);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\ttop.layer.alert(\"提交失败\");\r\n");
      out.write("\t\t\t\t\t\t\t\ttop.layer.close(maskLayer);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}, 100);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
