/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2016-12-16 03:35:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cn.nubia.common.*;
import cn.nubia.rbac.model.SysUser;
import cn.nubia.framework.cache.*;
import cn.nubia.framework.core.HttpCookie;
import cn.nubia.framework.crypto.Des;
import cn.nubia.framework.crypto.PaddingMode;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("cn.nubia.common");
    _jspx_imports_packages.add("cn.nubia.framework.cache");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("cn.nubia.rbac.model.SysUser");
    _jspx_imports_classes.add("cn.nubia.framework.core.HttpCookie");
    _jspx_imports_classes.add("cn.nubia.framework.crypto.Des");
    _jspx_imports_classes.add("cn.nubia.framework.crypto.PaddingMode");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	SysUser sysuser = (SysUser) session.getAttribute(Define.SESSION_IN_USER);
	if (sysuser == null) {
		HttpCookie cookie = new HttpCookie(request, response);
		String workId = cookie.getValue(Define.COOKIE_IN_USERID);
		if (workId != null) {
			Des des = new Des(64, PaddingMode.PKCS5Padding);
			if (CacheUtil.getCache().get(des.cbc_encrypt(Define.DES_KEY, Define.DES_VALUE,workId)) != null) {
				sysuser = (SysUser) CacheUtil.getCache().get(des.cbc_encrypt(Define.DES_KEY,Define.DES_VALUE, workId)).getValue();
			}
			if (sysuser != null) {
				response.sendRedirect("model.action");
			}
		}
	} else {
		response.sendRedirect("model.action");
	}

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\" />\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-cache\" />\n");
      out.write("<meta http-equiv=\"Expires\" content=\"0\" />\n");
      out.write("<title>nubia生产同步管理系统</title>\n");
      out.write("<link href=\"res/css/login.css?v=3\" rel=\"stylesheet\">\n");
      out.write("<script src=\"res/js/jquery-1.11.1.min.js?v=3\"></script>\n");
      out.write("<script src=\"res/js/jquery-ui.min.js?v=3\"></script>\n");
      out.write("<script>\n");
      out.write("\tvar cookieName = 'task_username';\n");
      out.write("\t//密码填写错误振动；\n");
      out.write("\tfunction rock() {\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction login() {\n");
      out.write("\t\tvar frm = $('form:eq(0)'), uv = frm[0].username.value, pv = frm[0].password.value, tip = $('h2:eq(0)');\n");
      out.write("\t\tif ($.trim(uv) == '') {\n");
      out.write("\t\t\t$('#loginDiv').effect(\"shake\", {\n");
      out.write("\t\t\t\ttimes : 3\n");
      out.write("\t\t\t}, 100, function() {\n");
      out.write("\t\t\t\t$('#username').focus();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t$('#password').attr(\"value\", \"\");\n");
      out.write("\t\t\t$('#codeDiv .note').show();\n");
      out.write("\n");
      out.write("\t\t} else if ($.trim(pv) == '') {\n");
      out.write("\t\t\t$('#loginDiv').effect(\"shake\", {\n");
      out.write("\t\t\t\ttimes : 3\n");
      out.write("\t\t\t}, 100, function() {\n");
      out.write("\t\t\t\t$('#password').focus();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t$('#password').attr(\"value\", \"\");\n");
      out.write("\t\t\t$('#codeDiv .note').show();\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\t$.post(\"login/check.action\", frm.serialize(), function(r) {\n");
      out.write("\t\t\t\tif (r == \"success\") {\n");
      out.write("\t\t\t\t\t$.cookie.set(cookieName, uv, 2678400);\n");
      out.write("\t\t\t\t\ttop.location.href = \"model.do\";\n");
      out.write("\t\t\t\t} else if (r == \"username_error\") {\n");
      out.write("\t\t\t\t\t$('#alert').show();\n");
      out.write("\t\t\t\t} else if (r == \"password_error\") {\n");
      out.write("\t\t\t\t\t$('#forget').show();\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\talert(\"系统出错,信息如下:\" + r);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t$(document).ready(function() {\n");
      out.write("\n");
      out.write("\t\tvar frm = $('form:eq(0)');\n");
      out.write("\t\tvar username = $.cookie.get(cookieName);\n");
      out.write("\t\tif (username) {\n");
      out.write("\t\t\tfrm[0].username.value = username;\n");
      out.write("\t\t\t$('#userDiv .note').hide();\n");
      out.write("\t\t\t$('#username').focus();\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\t$('#password').focus();\n");
      out.write("\t\t}\n");
      out.write("\t\tfrm.keypress(function(e) {\n");
      out.write("\t\t\tif (e.keyCode == 13) {\n");
      out.write("\t\t\t\tlogin();\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\tif (top != self)\n");
      out.write("\t\t\ttop.location.href = \"index.jsp\";\n");
      out.write("\t\t//初始化；\n");
      out.write("\t\t$('#alert').hide();\n");
      out.write("\t\t$('#forget').hide();\n");
      out.write("\n");
      out.write("\t\t//\n");
      out.write("\t\t$('#username').focusin(function() {\n");
      out.write("\t\t\t$('#TMark').removeClass('hit');\n");
      out.write("\t\t\t$('#forget').hide();\n");
      out.write("\t\t}).focusout(function() {\n");
      out.write("\t\t\tif (this.value == '') {\n");
      out.write("\t\t\t\t$('#userDiv .note').show();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t;\n");
      out.write("\t\t\t$('#TMark').addClass('hit');\n");
      out.write("\t\t}).mouseup(function() {\n");
      out.write("\t\t\tif (this.value != '') {\n");
      out.write("\t\t\t\t$('#userDiv .note').hide();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\t$('#password').focusin(function() {\n");
      out.write("\t\t\t$('#PMark').removeClass('hit');\n");
      out.write("\t\t\t$('#forget').hide();\n");
      out.write("\t\t}).focusout(function() {\n");
      out.write("\t\t\tif (this.value == '') {\n");
      out.write("\t\t\t\t$('#codeDiv .note').show();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t$('#PMark').addClass('hit');\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t$('#stay_css,#stay_label').mousedown(function() {\n");
      out.write("\t\t\tif ($('#stay_css').attr(\"class\") == 'checkBox') {\n");
      out.write("\t\t\t\t$('#stay_css').addClass('press');\n");
      out.write("\t\t\t\t$('.stay_label_txt').addClass('blod');\n");
      out.write("\t\t\t\t$('#stay').attr(\"value\", \"1\");\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\t$('#stay_css').addClass('press2');\n");
      out.write("\t\t\t\t$('.stay_label_txt').removeClass('blod');\n");
      out.write("\t\t\t\t$('#stay').attr(\"value\", \"0\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}).mouseup(function() {\n");
      out.write("\t\t\t$('#stay_css').removeClass('press').removeClass('press2');\n");
      out.write("\t\t\t$('#stay_css').toggleClass('checked').toggleClass('checkBox');\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t$('#submit').mousedown(function() {\n");
      out.write("\t\t\t$('#submit').css(\"background-position\", \"0px -583px\");\n");
      out.write("\t\t}).mouseup(function() {\n");
      out.write("\t\t\t$('#submit').css(\"background-position\", \"0px -555px\");\n");
      out.write("\t\t})\n");
      out.write("\n");
      out.write("\t\t$('#username').keydown(function() {\n");
      out.write("\t\t\t$('#userDiv .note').hide();\n");
      out.write("\t\t});\n");
      out.write("\t\t$('#password').keydown(function() {\n");
      out.write("\t\t\t$('#codeDiv .note').hide();\n");
      out.write("\t\t});\n");
      out.write("\t\t$('#closeA').click(function() {\n");
      out.write("\t\t\t$('#alert').fadeOut();\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t//提交；\n");
      out.write("\t\t$('#submit').click(function() {\n");
      out.write("\t\t\tlogin();\n");
      out.write("\t\t})\n");
      out.write("\t})\n");
      out.write("\n");
      out.write("\t//cookie\n");
      out.write("\t$.cookie = {\n");
      out.write("\t\tget : function(name) {\n");
      out.write("\t\t\tvar a = document.cookie.match(new RegExp(\"(^| )\" + name + \"=([^;]*)(;|$)\"));\n");
      out.write("\t\t\treturn a ? unescape(a[2]) : null;\n");
      out.write("\t\t},\n");
      out.write("\t\tset : function(name, value, seconds, path, domain, secure) {\n");
      out.write("\t\t\tvar a = new Date();\n");
      out.write("\t\t\ta.setTime(a.getTime() + seconds);\n");
      out.write("\t\t\tdocument.cookie = escape(name) + '=' + escape(value) + (a ? '; expires=' + a.toGMTString() : '') + (path ? '; path=' + path : '/') + (domain ? '; domain=' + domain : '') + (secure ? '; secure' : '');\n");
      out.write("\t\t},\n");
      out.write("\t\tclear : function(name) {\n");
      out.write("\t\t\tvar a = new Date();\n");
      out.write("\t\t\ta.setTime(a.getTime() - 1);\n");
      out.write("\t\t\tdocument.cookie = name + '=null;expires=' + a.toGMTString();\n");
      out.write("\t\t}\n");
      out.write("\t};\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"alert\">\n");
      out.write("\t\t<h3 id=\"messge\">对不起，您输入的帐号不存在！</h3>\n");
      out.write("\t\t<div id=\"description\">\n");
      out.write("\t\t\t<p>请确保您的帐号是正确的，如给您的工作带来不便敬请谅解！</p>\n");
      out.write("\t\t\t<p style=\"text-align: right\">\n");
      out.write("\t\t\t\t<input id=\"closeA\" type=\"button\" value=\"好的，知道了\">\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"wrap\">\n");
      out.write("\t\t<div id=\"loginDiv\">\n");
      out.write("\t\t\t<div id=\"logo\"></div>\n");
      out.write("\t\t\t<form>\n");
      out.write("\t\t\t\t<div id=\"userDiv\">\n");
      out.write("\t\t\t\t\t<div id=\"TMark\" class=\"inputMark hit\"></div>\n");
      out.write("\t\t\t\t\t<input name=\"username\" id=\"username\" class=\"field\" type=\"text\" maxlength='16' tabindex=\"1\" autocomplete=\"off\">\n");
      out.write("\t\t\t\t\t<div class=\"note\">请输入账号</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"codeDiv\">\n");
      out.write("\t\t\t\t\t<div id=\"PMark\" class=\"inputMark hit\"></div>\n");
      out.write("\t\t\t\t\t<input name=\"password\" id=\"password\" class=\"field\" type=\"password\" maxlength='16' tabindex=\"2\">\n");
      out.write("\t\t\t\t\t<div class=\"note\">请输入密码</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div id=\"submit\" class=\"submit\" title=\"登录\"></div>\n");
      out.write("\t\t\t\t\t<!--密码不正确提示-->\n");
      out.write("\t\t\t\t\t<div id=\"forget\">\n");
      out.write("\t\t\t\t\t\t<div id=\"forget_top\"></div>\n");
      out.write("\t\t\t\t\t\t<div id=\"forget_middle\">\n");
      out.write("\t\t\t\t\t\t\t<div id=\"forget_description\">\n");
      out.write("\t\t\t\t\t\t\t\t<dt>你输入的密码不正确</dt>\n");
      out.write("\t\t\t\t\t\t\t\t<dd>请使用正确的密码再次登录;</dd>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"forget_bottom\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div id=\"remeber\">\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"stay\" name=\"stay\" value=\"0\" checked=\"\" hidefocus=\"\" style=\"display: none;\"><span id=\"stay_css\" class=\"checkBox\"></span><span id=\"stay_label\" class=\"stay_label_txt\">记住密码，保持我的登录状态.</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div id=\"copyright\">2015 © 努比亚技术有限公司</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
