/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2017-01-13 09:44:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class workspace_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1471862222000L));
    _jspx_dependants.put("jar:file:/data/wwwroot/channel-webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/nubia.tld", Long.valueOf(1472004632000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\t<title>全渠道数据中心平台</title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/res/css/style.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/res/bootstrap/core/bootstrap-modal.css\">\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"http://static.nubia.cn/images/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"hd\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"hd-logo\">\n");
      out.write("\t\t\t\t<div class=\"hd-bg-logo\"></div>\n");
      out.write("\t\t\t\t<div class=\"hd-title\">全渠道数据中心平台</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"hd-right\">\n");
      out.write("\t\t\t\t<div class=\"welcome\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${realname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ，欢迎您使用全渠道数据中心平台！</div>\n");
      out.write("\t\t\t\t<div class=\"btn-groups\">\n");
      out.write("\t\t\t\t\t<div class=\"icon icon-hd-usr\" title=\"个人中心\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"icon icon-feedback\" title=\"帮助\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"icon icon-edit\" data-toggle=\"modal\" data-target=\"#myModal\" title=\"问题反馈\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"icon icon-logout\" title=\"退出\" onClick=\"System.logout();\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"row nav\">\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"sidebar\" id=\"basic-menu\">\n");
      out.write("\t\t<ul class=\"menu\">\n");
      out.write("\t\t\t<li class=\"menu-item\">\n");
      out.write("\t\t\t\t");
      out.write("\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"iframe-con\">\n");
      out.write("\t\t<iframe src=\"/marketOverall/page/index/list.do\" name=\"iFrame\" onload=\"this.height=iFrame.document.body.scrollHeight\" frameborder=\"0\" id=\"iframe-con\" height=\"600px\"></iframe>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("\t\taria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\">×</button>\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">问题反馈</h4>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t<form class=\"form-horizontal\">\n");
      out.write("\t\t\t\t\t<textarea class=\"form-control\" rows=\"10\" placeholder=\"请输入反馈信息\" name=\"feedback\" id=\"feedback\" style=\"width: 95%;\"></textarea>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"savefeedback\">提交</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"ft\">\n");
      out.write("\t\t<ul class=\"ft-links\">\n");
      out.write("\t\t\t<li class=\"items-link\"><a href=\"http://www.nubia.com/service.php?sid=6\" target=\"_blank\">关于我们</a></li>|\n");
      out.write("\t\t\t<li class=\"items-link\"><a href=\"http://www.nubia.com/service.php?sid=7\" target=\"_blank\">联系我们</a></li>|\n");
      out.write("\t\t\t<li class=\"items-link\"><a href=\"http://www.nubia.com/news.php\" target=\"_blank\">新闻中心</a></li>|\n");
      out.write("\t\t\t<li class=\"items-link\"><a href=\"http://hr.nubia.com\" target=\"_blank\">加入我们</a></li>|\n");
      out.write("\t\t\t<li class=\"items-link\"><a href=\"http://www.nubia.com/gongyi.php\" target=\"_blank\">公益</a></li>|\n");
      out.write("\t\t\t<li class=\"items-link\"><a href=\"http://www.nubia.com/starsky.php\" target=\"_blank\">星空之约</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<p class=\"nb-footer-info\"> 2012-2016 努比亚 版权所有 <a href=\"http://www.miibeian.gov.cn/\" target=\"_blank\">粤ICP备10006213号-2</a> ICP经营许可证编号：粤B2-20120688<a href=\"http://szcert.ebs.org.cn/D52B1891-CB9A-4FD0-8BC6-1D5650B567CE\" target=\"_blank\" style=\"margin-right: 5px;margin-left: 3px;\"><img src=\"http://static.nubia.cn/images/govIcon.png\" title=\"深圳市市场监督管理局企业主体身份公示\" alt=\"深圳市市场监督管理局企业主体身份公示\" border=\"0\" style=\"border-width:0px;border:hidden; border:none;vertical-align: middle;height: 18px;\"></a> 努比亚技术有限公司</p>\n");
      out.write("\t</div>\n");
      out.write("\t<script src=\"/res/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"/res/bootstrap/core/bootstrap.min.js\"></script>\n");
      out.write("\t<script src=\"/res/common/common.js\"></script>\n");
      out.write("\t<script src=\"/res/layer/layer.js\"></script>\n");
      out.write("\t<script src=\"/workspace.js?v=3\"></script>\n");
      out.write("\t<script>\n");
      out.write("\n");
      out.write("\t\tvar operationTag = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${operationTag}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' || [];\n");
      out.write("\t\tvar operTags = [];\n");
      out.write("\t\tif (!$.isArray(operationTag)) {\n");
      out.write("\t\t\toperTags = JSON.parse(operationTag);\n");
      out.write("\t\t}\n");
      out.write("\t\tvar isInArray = function(id, ids) {\n");
      out.write("\t\t\treturn $.inArray(id, ids) !== -1;\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\tvar isDelPermit = function() {\n");
      out.write("\t\t\treturn isInArray('deleteOpt', operTags) || isInArray('superOpt', operTags);\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\tvar isAddPermit = function () {\n");
      out.write("\t\t\treturn isInArray('addOpt', operTags) || isInArray('superOpt', operTags);\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\tvar isUptPermit = function () {\n");
      out.write("\t\t\treturn isInArray('updateOpt', operTags) || isInArray('superOpt', operTags);\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\tvar isQryPermit = function () {\n");
      out.write("\t\t\treturn isInArray('queryOpt', operTags) || isInArray('superOpt', operTags);\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\tvar isExpPermit = function () {\n");
      out.write("\t\t\treturn isInArray('exportOpt', operTags) || isInArray('superOpt', operTags);\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\tvar isSuperPermit = function() {\n");
      out.write("\t\t\treturn isInArray('superOpt', operTags) || isInArray('superOpt', operTags);\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\tvar isImpPermit = function() {\n");
      out.write("\t\t\treturn isInArray('importOpt', operTags) || isInArray('superOpt', operTags);\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /workspace.jsp(30,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty topMenus}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /workspace.jsp(31,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("item");
    // /workspace.jsp(31,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/workspace.jsp(31,4) '${topMenus}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${topMenus}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<li><a href=\"javascript:;\" class=\"nav-rowbar\" id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" title=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.mainHref}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></li>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
