/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2016-05-06 03:25:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.route.container;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addOrEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/route/container/../../include/head.jsp", Long.valueOf(1460338154000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1460446166000L));
    _jspx_dependants.put("jar:file:/data/wwwroot/nubia_nps_admin/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>应用管理</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path;
	request.setAttribute("ctx", basePath);

      out.write(" \r\n");
      out.write("<script>\r\n");
      out.write("var ctx =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/res/bootstrap/core/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/res/bootstrap/core/bootstrap-theme.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/res/bootstrap-table/bootstrap-table.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/res/common/common.css\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"/res/jquery.js\"></script>\r\n");
      out.write("<script src=\"/res/jquery.json-2.2.min.js\"></script>\r\n");
      out.write("<script src=\"/res/bootstrap/core/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/res/bootstrap-table/bootstrap-table.min.js\"></script>\r\n");
      out.write("<script src=\"/res/layer/layer.js\"></script>\r\n");
      out.write("<script src=\"/res/common/common.js\"></script>\r\n");
      out.write("<script src=\"/res/My97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("<script src=\"/res/DateUtil.js\"></script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/route/container/addOrEdit.js\" ></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("    ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("    \r\n");
        out.write("    ");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /route/container/addOrEdit.jsp(11,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceContainer.id>0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t        <h2 class=\"page-header\">容器资源编辑</h2>\r\n");
        out.write("\t      <form class=\"form-horizontal\">\r\n");
        out.write("\t      <input id=\"id\" name=\"id\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceContainer.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" type=\"hidden\">\r\n");
        out.write("\t      <div class=\"form-group\">\r\n");
        out.write("\t          <label for=\"appId\" class=\"col-sm-2 control-label\">名称</label>\r\n");
        out.write("\t          <div class=\"col-sm-8\">\r\n");
        out.write("\t              <input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceContainer.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("\t          </div>\r\n");
        out.write("\t          <div class=\"col-sm-2 error-msg\"></div>\r\n");
        out.write("\t      </div>\r\n");
        out.write("\t      <div class=\"form-group\">\r\n");
        out.write("\t          <label for=\"host\" class=\"col-sm-2 control-label\">主机</label>\r\n");
        out.write("\t          <div class=\"col-sm-8\">\r\n");
        out.write("\t              <input type=\"text\" class=\"form-control\" id=\"host\" name=\"host\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceContainer.host }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("\t          </div>\r\n");
        out.write("\t          <div class=\"col-sm-2 error-msg\"></div>\r\n");
        out.write("\t      </div>\r\n");
        out.write("\t       <div class=\"form-group\">\r\n");
        out.write("              <label for=\"port\" class=\"col-sm-2 control-label\">端口号</label>\r\n");
        out.write("              <div class=\"col-sm-8\">\r\n");
        out.write("                  <input type=\"text\" class=\"form-control\" id=\"port\" name=\"port\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceContainer.port }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("              </div>\r\n");
        out.write("              <div class=\"col-sm-2 error-msg\"></div>\r\n");
        out.write("          </div>\r\n");
        out.write("\t      <div class=\"form-group\">\r\n");
        out.write("\t          <label for=\"uniqueId\" class=\"col-sm-2 control-label\">唯一Id</label>\r\n");
        out.write("\t          <div class=\"col-sm-8\">\r\n");
        out.write("\t              <input type=\"text\" class=\"form-control\" id=\"uniqueId\" name=\"uniqueId\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceContainer.uniqueId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("\t          </div>\r\n");
        out.write("\t          <div class=\"col-sm-2 error-msg\"></div>\r\n");
        out.write("\t      </div>\r\n");
        out.write("\t      <div class=\"form-group\">\r\n");
        out.write("\t          <label for=\"serviceType\" class=\"col-sm-2 control-label\">服务类型</label>\r\n");
        out.write("              <div class=\"col-sm-8\">\r\n");
        out.write("              <input type=\"hidden\" id=\"serviceTypeValue\" name=\"serviceTypeValue\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceContainer.serviceType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("                  <select class=\"form-control\" id=\"serviceType\" name=\"serviceType\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceContainer.serviceType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("                        <option value=\"API\">API</option>\r\n");
        out.write("                        <option value=\"SERVER\">SERVER</option>\r\n");
        out.write("                        <option value=\"ACCESS\">ACCESS</option>\r\n");
        out.write("                        <option value=\"ROUTE\">ROUTE</option>\r\n");
        out.write("                  </select>\r\n");
        out.write("              </div>\r\n");
        out.write("              <div class=\"col-sm-2 error-msg\"></div>\r\n");
        out.write("\t      </div>\r\n");
        out.write("\t       <div class=\"form-group\">\r\n");
        out.write("\t           <div class=\"col-sm-offset-2 col-sm-8\">\r\n");
        out.write("\t               <button id=\"save-btn\" type=\"button\" class=\"btn btn-primary\">提交</button>\r\n");
        out.write("\t               <button id=\"back-btn\" type=\"button\" class=\"btn btn-default\">返回</button>\r\n");
        out.write("\t           </div>\r\n");
        out.write("\t       </div>\r\n");
        out.write("\t   </form>\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t      <h2 class=\"page-header\">容器资源添加</h2>\r\n");
        out.write("          <form class=\"form-horizontal\">\r\n");
        out.write("          <input id=\"id\" name=\"id\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceContainer.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" type=\"hidden\">\r\n");
        out.write("          <div class=\"form-group\">\r\n");
        out.write("              <label for=\"appId\" class=\"col-sm-2 control-label\">名称</label>\r\n");
        out.write("              <div class=\"col-sm-8\">\r\n");
        out.write("                  <input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceContainer.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("              </div>\r\n");
        out.write("              <div class=\"col-sm-2 error-msg\"></div>\r\n");
        out.write("          </div>\r\n");
        out.write("          <div class=\"form-group\">\r\n");
        out.write("              <label for=\"host\" class=\"col-sm-2 control-label\">主机</label>\r\n");
        out.write("              <div class=\"col-sm-8\">\r\n");
        out.write("                  <input type=\"text\" class=\"form-control\" id=\"host\" name=\"host\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceContainer.host }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("              </div>\r\n");
        out.write("              <div class=\"col-sm-2 error-msg\"></div>\r\n");
        out.write("          </div>\r\n");
        out.write("           <div class=\"form-group\">\r\n");
        out.write("              <label for=\"port\" class=\"col-sm-2 control-label\">端口号</label>\r\n");
        out.write("              <div class=\"col-sm-8\">\r\n");
        out.write("                  <input type=\"text\" class=\"form-control\" id=\"port\" name=\"port\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceContainer.port }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("              </div>\r\n");
        out.write("              <div class=\"col-sm-2 error-msg\"></div>\r\n");
        out.write("          </div>\r\n");
        out.write("          <div class=\"form-group\">\r\n");
        out.write("              <label for=\"uniqueId\" class=\"col-sm-2 control-label\">唯一Id</label>\r\n");
        out.write("              <div class=\"col-sm-8\">\r\n");
        out.write("                  <input type=\"text\" class=\"form-control\" id=\"uniqueId\" name=\"uniqueId\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceContainer.uniqueId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("              </div>\r\n");
        out.write("              <div class=\"col-sm-2 error-msg\"></div>\r\n");
        out.write("          </div>\r\n");
        out.write("          <div class=\"form-group\">\r\n");
        out.write("              <label for=\"serviceType\" class=\"col-sm-2 control-label\">服务类型</label>\r\n");
        out.write("              <div class=\"col-sm-8\">\r\n");
        out.write("                  <select class=\"form-control\" id=\"serviceType\" name=\"serviceType\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceContainer.serviceType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("                        <option value=\"API\">API</option>\r\n");
        out.write("                        <option value=\"SERVER\">SERVER</option>\r\n");
        out.write("                        <option value=\"ACCESS\">ACCESS</option>\r\n");
        out.write("                        <option value=\"ROUTE\">ROUTE</option>\r\n");
        out.write("                  </select>\r\n");
        out.write("              </div>\r\n");
        out.write("              <div class=\"col-sm-2 error-msg\"></div>\r\n");
        out.write("          </div>\r\n");
        out.write("           <div class=\"form-group\">\r\n");
        out.write("               <div class=\"col-sm-offset-2 col-sm-8\">\r\n");
        out.write("                   <button id=\"save-btn\" type=\"button\" class=\"btn btn-primary\">提交</button>\r\n");
        out.write("                   <button id=\"back-btn\" type=\"button\" class=\"btn btn-default\">返回</button>\r\n");
        out.write("               </div>\r\n");
        out.write("           </div>\r\n");
        out.write("       </form>\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
