/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2015-11-02 09:30:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ztemt.v5server.common.*;
import com.ztemt.rbac.model.SysUser;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.ztemt.v5server.common");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ztemt.rbac.model.SysUser");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 
	SysUser employee=(SysUser)session.getAttribute(Define.SESSION_IN_EMPLOYEE);
	if(employee==null){
		HttpCookie cookie=new HttpCookie(request,response);
		String workId=cookie.getValue(Define.COOKIE_IN_WORKID);
		if(workId!=null){
			employee=Cache.get(DES.decrypt(workId));
			if(employee!=null){
				response.sendRedirect(request.getContextPath()+"/workspace/workspace.action");
			}
		}
	}else{
		response.sendRedirect(request.getContextPath()+"/workspace/workspace.action");
	}

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n");
      out.write("\t<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
      out.write("\t<meta http-equiv=\"Expires\" content=\"0\"/>\r\n");
      out.write("<title>V5后台管理系统</title>\r\n");
      out.write("<link href=\"res/css/login.css?v=3\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"res/js/jquery.js?v=3\"></script>\r\n");
      out.write("<script src=\"res/js/jquery-ui.min.js?v=3\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("var cookieName='task_username';\r\n");
      out.write("//密码填写错误振动；\r\n");
      out.write("function rock(){}\r\n");
      out.write("\r\n");
      out.write("function login(){\r\n");
      out.write("\tvar frm=$('form:eq(0)'),uv=frm[0].username.value,pv=frm[0].password.value,tip=$('h2:eq(0)');\r\n");
      out.write("\tif($.trim(uv)==''){\r\n");
      out.write("\t\t$('#loginDiv').effect(\"shake\", { times:3 }, 100, function(){$('#username').focus();});$('#password').attr(\"value\",\"\");$('#codeDiv .note').show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}else if($.trim(pv)==''){\r\n");
      out.write("\t\t$('#loginDiv').effect(\"shake\", { times:3 }, 100, function(){$('#password').focus();});$('#password').attr(\"value\",\"\");$('#codeDiv .note').show();\t\t\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$.post(\"login/check.action\",frm.serialize(),function(r){\t\t\t\t\r\n");
      out.write("\t\t\tif(r==\"success\"){\r\n");
      out.write("\t\t\t\t$.cookie.set(cookieName,uv,2678400);\r\n");
      out.write("\t\t\t\ttop.location.href=\"workspace/workspace.action\";\r\n");
      out.write("\t\t\t}else if(r==\"username_error\"){\r\n");
      out.write("\t\t\t\t$('#alert').show();\r\n");
      out.write("\t\t\t}else if(r==\"password_error\"){\r\n");
      out.write("\t\t\t\t$('#forget').show();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"系统出错,信息如下:\"+r);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("  var frm=$('form:eq(0)');\r\n");
      out.write("\tvar username=$.cookie.get(cookieName);\r\n");
      out.write("\tif(username){\r\n");
      out.write("\t\tfrm[0].username.value=username;\r\n");
      out.write("\t\t$('#userDiv .note').hide();\r\n");
      out.write("\t\t$('#username').focus();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$('#password').focus();\r\n");
      out.write("\t}\r\n");
      out.write("    frm.keypress(function (e) {\r\n");
      out.write("        if (e.keyCode == 13){ \r\n");
      out.write("      \t \tlogin();\r\n");
      out.write("         \treturn false;\r\n");
      out.write("        }            \r\n");
      out.write("    });\r\n");
      out.write("\tif(top!=self) top.location.href=\"index.jsp\";\r\n");
      out.write(" //初始化；\r\n");
      out.write(" $('#alert').hide();\r\n");
      out.write(" $('#forget').hide();\r\n");
      out.write("\r\n");
      out.write(" //\r\n");
      out.write(" $('#username').focusin(function(){$('#TMark').removeClass('hit');$('#forget').hide();}).focusout(function(){if(this.value==''){$('#userDiv .note').show();};$('#TMark').addClass('hit');}).mouseup(function(){if(this.value!=''){$('#userDiv .note').hide();}});\r\n");
      out.write(" $('#password').focusin(function(){$('#PMark').removeClass('hit');$('#forget').hide();}).focusout(function(){if(this.value==''){$('#codeDiv .note').show();}$('#PMark').addClass('hit');});\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("$('#stay_css,#stay_label').mousedown(function(){if($('#stay_css').attr(\"class\")=='checkBox'){$('#stay_css').addClass('press');$('.stay_label_txt').addClass('blod');$('#stay').attr(\"value\",\"1\");}else{$('#stay_css').addClass('press2');$('.stay_label_txt').removeClass('blod');$('#stay').attr(\"value\",\"0\");} })\r\n");
      out.write(" \t\t\t.mouseup(function(){$('#stay_css').removeClass('press').removeClass('press2');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#stay_css').toggleClass('checked').toggleClass('checkBox');});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write(" $('#submit').mousedown(function(){$('#submit').css(\"background-position\",\"0px -583px\");})\r\n");
      out.write(" \t\t\t .mouseup(function(){$('#submit').css(\"background-position\",\"0px -555px\");})\r\n");
      out.write("\t\t\t \r\n");
      out.write(" $('#username').keydown(function(){$('#userDiv .note').hide();});\r\n");
      out.write(" $('#password').keydown(function(){$('#codeDiv .note').hide();});\r\n");
      out.write(" $('#closeA').click(function(){$('#alert').fadeOut();});\r\n");
      out.write("\r\n");
      out.write(" //提交；\r\n");
      out.write(" $('#submit').click(function(){login();})\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("//cookie\r\n");
      out.write("$.cookie={\r\n");
      out.write("    get:function(name){\r\n");
      out.write("        var a=document.cookie.match(new RegExp(\"(^| )\"+name+\"=([^;]*)(;|$)\"));\r\n");
      out.write("        return a?unescape(a[2]):null;\r\n");
      out.write("    },\r\n");
      out.write("    set:function(name,value,seconds, path, domain, secure) {\r\n");
      out.write("        var a= new Date();\r\n");
      out.write("        a.setTime(a.getTime() + seconds);\r\n");
      out.write("        document.cookie =\r\n");
      out.write("            escape(name) + '=' + escape(value)\r\n");
      out.write("            + (a ? '; expires=' + a.toGMTString() : '')\r\n");
      out.write("            + (path ? '; path=' + path : '/')\r\n");
      out.write("            + (domain ? '; domain=' + domain : '')\r\n");
      out.write("            + (secure ? '; secure' : '');\r\n");
      out.write("    },\r\n");
      out.write("    clear:function(name) {\r\n");
      out.write("        var a= new Date();\r\n");
      out.write("        a.setTime(a.getTime() - 1);\r\n");
      out.write("        document.cookie= name+'=null;expires='+a.toGMTString();\r\n");
      out.write("    }\r\n");
      out.write(" };\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"alert\">\r\n");
      out.write("<h3 id=\"messge\">对不起，您输入的帐号不存在！</h3>\r\n");
      out.write("<div id=\"description\">\r\n");
      out.write("<p>请确保您的帐号是正确的，如给您的工作带来不便敬请谅解！</p>\r\n");
      out.write("<p style=\"text-align:right\"><input  id=\"closeA\" type=\"button\" value=\"好的，知道了\"></p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("<div id=\"loginDiv\">\r\n");
      out.write("<div id=\"logo\"></div>\r\n");
      out.write("<form>\r\n");
      out.write("<div id=\"userDiv\">\r\n");
      out.write("<div id=\"TMark\" class=\"inputMark hit\"></div>\r\n");
      out.write("<input name=\"username\" id=\"username\" class=\"field\" type=\"text\" maxlength='16' tabindex=\"1\" autocomplete=\"off\">\r\n");
      out.write("<div class=\"note\" >请输入账号</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"codeDiv\">\r\n");
      out.write("<div id=\"PMark\" class=\"inputMark hit\"></div>\r\n");
      out.write("<input name=\"password\" id=\"password\" class=\"field\" type=\"password\" maxlength='16' tabindex=\"2\">\r\n");
      out.write("<div class=\"note\">请输入密码</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"submit\" class=\"submit\" title=\"登录\" ></div>\r\n");
      out.write("<!--密码不正确提示-->\r\n");
      out.write("<div id=\"forget\">\r\n");
      out.write("<div id=\"forget_top\"></div>\r\n");
      out.write("<div id=\"forget_middle\">\r\n");
      out.write("<div id=\"forget_description\">\r\n");
      out.write("<dt>你输入的密码不正确</dt>\r\n");
      out.write("<dd>\r\n");
      out.write("请使用正确的密码再次登录;\r\n");
      out.write("</dd>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"forget_bottom\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"remeber\"><input type=\"checkbox\"  id=\"stay\" name=\"stay\" value=\"0\" checked=\"\" hidefocus=\"\" style=\"display:none;\" ><span id=\"stay_css\" class=\"checkBox\" ></span><span id=\"stay_label\" class=\"stay_label_txt\" >记住密码，保持我的登录状态.</span></div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"copyright\">2012 © </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
