/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2015-11-02 09:30:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class left_005fuser_005fguide_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/ztemt.tld", Long.valueOf(1435560385000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<ul>\r\n");
      //  rbac:privilege
      com.ztemt.tag.PrivilegeTag _jspx_th_rbac_005fprivilege_005f0 = (com.ztemt.tag.PrivilegeTag) _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.get(com.ztemt.tag.PrivilegeTag.class);
      _jspx_th_rbac_005fprivilege_005f0.setPageContext(_jspx_page_context);
      _jspx_th_rbac_005fprivilege_005f0.setParent(null);
      // /left_user_guide.jsp(3,0) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_rbac_005fprivilege_005f0.setTest("faq/listPhoneType.action");
      int _jspx_eval_rbac_005fprivilege_005f0 = _jspx_th_rbac_005fprivilege_005f0.doStartTag();
      if (_jspx_eval_rbac_005fprivilege_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<li class=\"active\"><a href=\"../faq/listPhoneType.action?st=");
          out.print(new java.util.Date().getTime());
          out.write("\">机型设置</a></li>\r\n");
          int evalDoAfterBody = _jspx_th_rbac_005fprivilege_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_rbac_005fprivilege_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f0);
        return;
      }
      _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f0);
      out.write('\r');
      out.write('\n');
      //  rbac:privilege
      com.ztemt.tag.PrivilegeTag _jspx_th_rbac_005fprivilege_005f1 = (com.ztemt.tag.PrivilegeTag) _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.get(com.ztemt.tag.PrivilegeTag.class);
      _jspx_th_rbac_005fprivilege_005f1.setPageContext(_jspx_page_context);
      _jspx_th_rbac_005fprivilege_005f1.setParent(null);
      // /left_user_guide.jsp(6,0) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_rbac_005fprivilege_005f1.setTest("userManual/listUserManual.action");
      int _jspx_eval_rbac_005fprivilege_005f1 = _jspx_th_rbac_005fprivilege_005f1.doStartTag();
      if (_jspx_eval_rbac_005fprivilege_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<li><a href=\"../userManual/listUserManual.action?st=");
          out.print(new java.util.Date().getTime());
          out.write("\">用户手册</a></li>\r\n");
          int evalDoAfterBody = _jspx_th_rbac_005fprivilege_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_rbac_005fprivilege_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f1);
        return;
      }
      _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f1);
      out.write('\r');
      out.write('\n');
      //  rbac:privilege
      com.ztemt.tag.PrivilegeTag _jspx_th_rbac_005fprivilege_005f2 = (com.ztemt.tag.PrivilegeTag) _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.get(com.ztemt.tag.PrivilegeTag.class);
      _jspx_th_rbac_005fprivilege_005f2.setPageContext(_jspx_page_context);
      _jspx_th_rbac_005fprivilege_005f2.setParent(null);
      // /left_user_guide.jsp(9,0) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_rbac_005fprivilege_005f2.setTest("faq/listFaq.action");
      int _jspx_eval_rbac_005fprivilege_005f2 = _jspx_th_rbac_005fprivilege_005f2.doStartTag();
      if (_jspx_eval_rbac_005fprivilege_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<li><a href=\"../faq/listFaq.action?st=");
          out.print(new java.util.Date().getTime());
          out.write("\">FAQ</a></li>\r\n");
          int evalDoAfterBody = _jspx_th_rbac_005fprivilege_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_rbac_005fprivilege_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f2);
        return;
      }
      _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f2);
      out.write('\r');
      out.write('\n');
      //  rbac:privilege
      com.ztemt.tag.PrivilegeTag _jspx_th_rbac_005fprivilege_005f3 = (com.ztemt.tag.PrivilegeTag) _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.get(com.ztemt.tag.PrivilegeTag.class);
      _jspx_th_rbac_005fprivilege_005f3.setPageContext(_jspx_page_context);
      _jspx_th_rbac_005fprivilege_005f3.setParent(null);
      // /left_user_guide.jsp(12,0) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_rbac_005fprivilege_005f3.setTest("faq/listFaqKeyword.action");
      int _jspx_eval_rbac_005fprivilege_005f3 = _jspx_th_rbac_005fprivilege_005f3.doStartTag();
      if (_jspx_eval_rbac_005fprivilege_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<li><a href=\"../faq/listFaqKeyword.action?st=");
          out.print(new java.util.Date().getTime());
          out.write("\">FAQ关键字</a></li>\r\n");
          int evalDoAfterBody = _jspx_th_rbac_005fprivilege_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_rbac_005fprivilege_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f3);
        return;
      }
      _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f3);
      out.write('\r');
      out.write('\n');
      //  rbac:privilege
      com.ztemt.tag.PrivilegeTag _jspx_th_rbac_005fprivilege_005f4 = (com.ztemt.tag.PrivilegeTag) _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.get(com.ztemt.tag.PrivilegeTag.class);
      _jspx_th_rbac_005fprivilege_005f4.setPageContext(_jspx_page_context);
      _jspx_th_rbac_005fprivilege_005f4.setParent(null);
      // /left_user_guide.jsp(15,0) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_rbac_005fprivilege_005f4.setTest("feedback/listFeedback.action");
      int _jspx_eval_rbac_005fprivilege_005f4 = _jspx_th_rbac_005fprivilege_005f4.doStartTag();
      if (_jspx_eval_rbac_005fprivilege_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<li><a href=\"../feedback/listFeedback.action?st=");
          out.print(new java.util.Date().getTime());
          out.write("&pageno=1\">用户反馈</a></li>\r\n");
          int evalDoAfterBody = _jspx_th_rbac_005fprivilege_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_rbac_005fprivilege_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f4);
        return;
      }
      _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f4);
      out.write('\r');
      out.write('\n');
      //  rbac:privilege
      com.ztemt.tag.PrivilegeTag _jspx_th_rbac_005fprivilege_005f5 = (com.ztemt.tag.PrivilegeTag) _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.get(com.ztemt.tag.PrivilegeTag.class);
      _jspx_th_rbac_005fprivilege_005f5.setPageContext(_jspx_page_context);
      _jspx_th_rbac_005fprivilege_005f5.setParent(null);
      // /left_user_guide.jsp(18,0) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_rbac_005fprivilege_005f5.setTest("feedbackimage/listFeedbackImage.action");
      int _jspx_eval_rbac_005fprivilege_005f5 = _jspx_th_rbac_005fprivilege_005f5.doStartTag();
      if (_jspx_eval_rbac_005fprivilege_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<li><a href=\"../feedbackimage/listFeedbackImage.action?st=");
          out.print(new java.util.Date().getTime());
          out.write("&pageno=1\">用户图片反馈</a></li>\r\n");
          int evalDoAfterBody = _jspx_th_rbac_005fprivilege_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_rbac_005fprivilege_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f5);
        return;
      }
      _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f5);
      out.write('\r');
      out.write('\n');
      //  rbac:privilege
      com.ztemt.tag.PrivilegeTag _jspx_th_rbac_005fprivilege_005f6 = (com.ztemt.tag.PrivilegeTag) _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.get(com.ztemt.tag.PrivilegeTag.class);
      _jspx_th_rbac_005fprivilege_005f6.setPageContext(_jspx_page_context);
      _jspx_th_rbac_005fprivilege_005f6.setParent(null);
      // /left_user_guide.jsp(21,0) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_rbac_005fprivilege_005f6.setTest("userManualUpdate/listUserManualUpdate.action");
      int _jspx_eval_rbac_005fprivilege_005f6 = _jspx_th_rbac_005fprivilege_005f6.doStartTag();
      if (_jspx_eval_rbac_005fprivilege_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<li><a href=\"../userManualUpdate/listUserManualUpdateModel.action?st=");
          out.print(new java.util.Date().getTime());
          out.write("\">宝典升级</a></li>\r\n");
          int evalDoAfterBody = _jspx_th_rbac_005fprivilege_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_rbac_005fprivilege_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f6);
        return;
      }
      _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f6);
      out.write('\r');
      out.write('\n');
      //  rbac:privilege
      com.ztemt.tag.PrivilegeTag _jspx_th_rbac_005fprivilege_005f7 = (com.ztemt.tag.PrivilegeTag) _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.get(com.ztemt.tag.PrivilegeTag.class);
      _jspx_th_rbac_005fprivilege_005f7.setPageContext(_jspx_page_context);
      _jspx_th_rbac_005fprivilege_005f7.setParent(null);
      // /left_user_guide.jsp(24,0) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_rbac_005fprivilege_005f7.setTest("handBook/listHandBook.action");
      int _jspx_eval_rbac_005fprivilege_005f7 = _jspx_th_rbac_005fprivilege_005f7.doStartTag();
      if (_jspx_eval_rbac_005fprivilege_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<li><a href=\"../handBook/listHandBookModel.action?st=");
          out.print(new java.util.Date().getTime());
          out.write("\">玩机手册</a></li>\r\n");
          int evalDoAfterBody = _jspx_th_rbac_005fprivilege_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_rbac_005fprivilege_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f7);
        return;
      }
      _005fjspx_005ftagPool_005frbac_005fprivilege_0026_005ftest.reuse(_jspx_th_rbac_005fprivilege_005f7);
      out.write("\r\n");
      out.write("</ul>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
